export const HEALTH_CONDITIONS = [
  {
    id: 'diabetes',
    nameKey: 'health.diabetes',
    avoid: ['white rice', 'maida', 'sugar', 'refined flour', 'potatoes in excess'],
    prefer: ['millets', 'bitter gourd', 'fenugreek', 'brown rice', 'barley'],
    promptNote: 'Avoid white rice, maida, sugar. Prefer millets, bitter gourd, low glycemic index foods.',
  },
  {
    id: 'hypertension',
    nameKey: 'health.hypertension',
    avoid: ['pickles', 'papad', 'excessive salt', 'processed foods'],
    prefer: ['garlic', 'leafy greens', 'potassium-rich vegetables'],
    promptNote: 'Low sodium diet. Avoid pickles and excess salt. Include garlic, leafy greens.',
  },
  {
    id: 'hypothyroidism',
    nameKey: 'health.hypothyroidism',
    avoid: ['raw cauliflower', 'raw cabbage', 'raw broccoli'],
    prefer: ['cooked cruciferous vegetables are fine', 'iodine rich foods'],
    promptNote: 'Avoid raw cruciferous vegetables. Cooked versions are fine.',
  },
  {
    id: 'pcos',
    nameKey: 'health.pcos',
    avoid: ['refined carbs', 'white bread', 'sugar'],
    prefer: ['flaxseeds', 'cinnamon', 'anti-inflammatory foods', 'whole grains'],
    promptNote: 'Avoid refined carbs. Include flaxseeds and cinnamon. PCOS disclaimer required.',
    requiresDisclaimer: true,
  },
  {
    id: 'heartDisease',
    nameKey: 'health.heartDisease',
    avoid: ['excessive ghee', 'fried foods', 'trans fats'],
    prefer: ['oats', 'turmeric', 'omega-3 rich foods'],
    promptNote: 'Minimal ghee. Prefer oats and turmeric. Heart-healthy cooking.',
  },
  {
    id: 'anaemia',
    nameKey: 'health.anaemia',
    avoid: ['tea with meals', 'coffee with meals'],
    prefer: ['spinach', 'jaggery', 'pomegranate', 'dates'],
    promptNote: 'Include spinach and jaggery. No tea or coffee with meals.',
  },
  {
    id: 'pregnancy',
    nameKey: 'health.pregnancy',
    avoid: ['raw papaya', 'raw pineapple', 'unpasteurized dairy'],
    prefer: ['folate-rich foods', 'iron-rich foods', 'calcium-rich foods'],
    promptNote: 'Focus on folate, iron, calcium. No raw papaya. Pregnancy disclaimer required.',
    requiresDisclaimer: true,
  },
  {
    id: 'kidneyDisease',
    nameKey: 'health.kidneyDisease',
    avoid: ['high potassium foods', 'excess protein', 'tomatoes in excess'],
    prefer: ['white rice', 'cabbage', 'cauliflower', 'apples'],
    promptNote: 'Low potassium, controlled protein diet.',
  },
];
