export const INDIAN_STATES = [
  { code: 'MH', name: 'Maharashtra', cuisine: 'Maharashtrian', variants: ['Kolhapuri', 'Vidarbha', 'Konkan', 'Mumbai'] },
  { code: 'WB', name: 'West Bengal', cuisine: 'Bengali', variants: ['Kolkata', 'Rural Bengali'] },
  { code: 'TN', name: 'Tamil Nadu', cuisine: 'Tamil', variants: ['Chennai', 'Chettinad', 'Kongu'] },
  { code: 'PB', name: 'Punjab', cuisine: 'Punjabi', variants: ['Amritsari', 'Ludhiana'] },
  { code: 'GJ', name: 'Gujarat', cuisine: 'Gujarati', variants: ['Saurashtra', 'Kathiawadi', 'Jain', 'Surti'] },
  { code: 'RJ', name: 'Rajasthan', cuisine: 'Rajasthani', variants: ['Jaipur', 'Jodhpur', 'Bikaner'] },
  { code: 'KL', name: 'Kerala', cuisine: 'Kerala', variants: ['Malabar', 'Kochi', 'Travancore'] },
  { code: 'UP', name: 'Uttar Pradesh', cuisine: 'Awadhi', variants: ['Lucknow', 'Varanasi', 'Agra'] },
  { code: 'BR', name: 'Bihar', cuisine: 'Bihari', variants: ['Patna', 'Mithila'] },
  { code: 'AP', name: 'Andhra Pradesh', cuisine: 'Andhra', variants: ['Vijayawada', 'Rayalaseema'] },
  { code: 'TS', name: 'Telangana', cuisine: 'Telangana', variants: ['Hyderabad', 'Karimnagar'] },
  { code: 'KA', name: 'Karnataka', cuisine: 'Karnataka', variants: ['Udupi', 'Coorg', 'Bangalore', 'North Karnataka'] },
  { code: 'MP', name: 'Madhya Pradesh', cuisine: 'Madhya Pradesh', variants: ['Indore', 'Bhopal', 'Gwalior'] },
  { code: 'OD', name: 'Odisha', cuisine: 'Odia', variants: ['Coastal Odisha', 'Inland Odisha'] },
  { code: 'AS', name: 'Assam', cuisine: 'Assamese', variants: ['Brahmaputra Valley', 'Barak Valley'] },
  { code: 'HR', name: 'Haryana', cuisine: 'Haryanvi', variants: ['Gurgaon', 'Rohtak'] },
  { code: 'HP', name: 'Himachal Pradesh', cuisine: 'Himachali', variants: ['Shimla', 'Kangra'] },
  { code: 'JK', name: 'Jammu & Kashmir', cuisine: 'Kashmiri', variants: ['Kashmiri Pandit', 'Dogra', 'Wazwan'] },
  { code: 'JH', name: 'Jharkhand', cuisine: 'Jharkhand', variants: ['Ranchi', 'Dhanbad'] },
  { code: 'CG', name: 'Chhattisgarh', cuisine: 'Chhattisgarhi', variants: ['Raipur', 'Bastar'] },
  { code: 'UK', name: 'Uttarakhand', cuisine: 'Garhwali', variants: ['Dehradun', 'Kumaon'] },
  { code: 'GA', name: 'Goa', cuisine: 'Goan', variants: ['North Goa', 'South Goa', 'Catholic Goan'] },
  { code: 'SK', name: 'Sikkim', cuisine: 'Sikkimese', variants: ['Gangtok'] },
  { code: 'NL', name: 'Nagaland', cuisine: 'Naga', variants: ['Kohima', 'Dimapur'] },
  { code: 'MN', name: 'Manipur', cuisine: 'Meitei', variants: ['Imphal'] },
  { code: 'ML', name: 'Meghalaya', cuisine: 'Khasi', variants: ['Shillong'] },
  { code: 'TR', name: 'Tripura', cuisine: 'Tripuri', variants: ['Agartala'] },
  { code: 'AR', name: 'Arunachal Pradesh', cuisine: 'Arunachali', variants: ['Itanagar'] },
];
